### ISSUE TITLE
examples directory doesn't make any sense

### ISSUE THREAD

**Issue by davisn** [textmagic/textmagic-rest-python#5]
The `examples` directory doesn't appear to include any actual examples.  Instead it looks like a clone of the `tests` directory.

**Comment by andreylarionov** [comment]
`examples` directory includes real-life examples of method calls. You can also run this examples as python tests. You will need to provide your API credentials. `tests` directory includes Mock tests that are designed primarily to provide the correct order of method invocation, correct signature of the methods and integrity of the library code. Mock tests do not require your API credentials, because they do not make real requests to the API.

**Comment by davisn** [comment]
As a user, I would expect something labelled as an "example" to be some small, self-contained piece of code with a well-defined goal (i.e., "send a message", "add a contact", etc.).  What am I supposed to draw from a test?

There's no direction on what the code is supposed to do or how to use it?  For example, running the scripts does absolutely nothing.  How do I actually *run* the tests?  What setup do I need to do, for example, to ensure my authentication information is found?  Will running the code have side-effects on my account and, if so, what are they?  These things need to be documented.

**Comment by andreylarionov** [comment]
Most likely a developer will look at the contents of `examples` and `tests` folders. Since classes in `examples` folder are inherited from `unittest.TestCase` so they can be run from the command line:
`python -m unittest examples` to run all examples or `python -m unittest examples.TestContacts` to run single class examples. But I agree that it is a good idea to specify this in README.md for example.
